final List<Map<String, String>> terbaru = [
    {
    'imagePath': 'images/solev.jpg',
    'cover': 'images/sololeveling.png',
    'title': 'Solo Leveling',
    'genre': 'Manhwa',
    'deskripsi':
        'Manhwa Solo Leveling yang dibuat oleh komikus bernama Chugong, H-goon KI, Soryeong ini bercerita tentang Dikenal sebagai Pemburu Terlemah dari Semua Umat Manusia, kontribusi pemburu peringkat-E Jinwoo Sung untuk penggerebekan sama dengan berusaha untuk tidak terbunuh. Sayangnya, di antara tagihan rumah sakit ibunya, biaya kuliah saudara perempuannya, dan kurangnya prospek pekerjaan, dia tidak punya pilihan selain terus mempertaruhkan nyawanya. Jadi ketika ada kesempatan untuk pembayaran yang lebih besar, dia mengambilnya...hanya untuk bertatap muka dengan makhluk yang kekuatannya melebihi apa pun yang pernah dia lihat! Dengan pemimpin partai kehilangan lengan dan satu-satunya penyembuh berantakan, dapatkah Jinwoo menemukan jalan keluar bagi mereka?',
    'status': 'tamat',
    'author': 'Chugong, H-goon KI, Soryeong',
    'artist': 'JANG Seong-rak (REDICE STUDIO), Redice Studio',
    'rilis': '2018',
    'awal': 'Chapter Awal: 00',
    'baru': 'Chapter Baru: 179',
    'isi': '179',
    'keterangan': 'on going',
  },
  {
    'imagePath': 'images/GOHS.jpg',
    'cover': 'images/goh.jpg',
    'title': 'The Gods Of Highschool',
    'genre': 'Manhwa',
    'deskripsi':
        'Manhwa The God of High School yang dibuat oleh komikus bernama PARK Yong-Je ini bercerita tentang Sementara sebuah pulau setengah menghilang dari muka bumi, sebuah organisasi misterius mengirimkan undangan untuk sebuah turnamen kepada setiap petarung yang terampil di dunia. Jika Anda menang, Anda dapat memiliki APA SAJA yang Anda inginkan. Mereka hanya merekrut yang terbaik untuk melawan yang terbaik dan mengklaim gelar Dewa SMA!.',
    'status': 'OnGoing',
    'author': 'PARK Yong-Je',
    'artist': 'PARK Yong-Je',
    'rilis': '2011',
    'awal': 'Chapter Awal: 00',
    'baru': 'Chapter Akhir: 537',
    'isi': '573',  
    'keterangan': 'on going',  
  },
  {
    'imagePath': 'images/aphoteosis.jpeg',
    'cover': 'images/aph.jpg',
    'title': 'Apotheosis',
    'genre': 'Manhua',
    'deskripsi':
        'Manhua Apotheosis yang dibuat oleh komikus bernama Gift Of Liberation ini bercerita tentang Luo Zheng, sekarang seorang budak yang rendah hati lahir sebagai putra tertua dari keluarga kaya. Karena penurunan keluarganya, penculikan saudara perempuannya oleh kekuatan yang kuat, dia sekarang hanya bisa diinjak oleh orang lain. Namun, surga tidak pernah menutup semua pintu keluar. Sebuah buku kuno yang ditinggalkan oleh ayahnya mengungkapkan teknik ilahi rahasia, memberi pembaca kekuatan besar! Tapi apa yang ada di balik kekuatan ini? Ini adalah kontes melawan takdir. ',
    'status': ' OnGoing',
    'author': 'Gift Of Liberation',
    'artist': 'Ranzai Studio',
    'rilis': ' 2015',
    'awal': 'Chapter Awal: 00',
    'baru': 'Chapter Akhir: 1129',
    'isi': '1129',
    'keterangan': 'on going',
  },
  {
    'imagePath': 'images/mp.jpg',
    'cover': 'images/martial peak.jpg',
    'title': 'Martial Peak',
    'genre': 'Manhua',
    'deskripsi':
        'Manhua Martial Peak yang dibuat oleh komikus bernama Momo (III) ini bercerita tentang Perjalanan ke puncak bela diri adalah perjalanan yang sepi, menyendiri, dan panjang. Dalam menghadapi kesulitan, Anda harus bertahan dan tetap pantang menyerah. Hanya dengan begitu Anda dapat menerobos dan melanjutkan perjalanan Anda untuk menjadi yang terkuat. Paviliun Tinggi Surga menguji murid-muridnya dengan cara yang paling keras untuk mempersiapkan mereka untuk perjalanan semacam itu. Suatu hari penyapu rendahan Yang Kai berhasil mendapatkan sebuah buku hitam misterius, menempatkannya di jalan menuju puncak dunia persilatan.',
    'status': ' OnGoing',
    'author': 'Momo (III)',
    'artist': ' Pikapi',
    'rilis': '2018',
    'awal': 'Chapter Awal: 2001',
    'baru': 'Chapter Akhir: 3340',
    'isi': '3340',
    'keterangan': 'on going',
  },
  {
    'imagePath': 'images/onepiece.jpg',
    'cover': 'images/op.jpg',
    'title': 'One Piece',
    'genre': 'Manga',
    'deskripsi':
        'Manga One Piece yang dibuat oleh komikus bernama ODA Eiichiro ini bercerita tentang Sebelum Raja Bajak Laut dieksekusi, dia menantang banyak bajak laut dunia untuk mencari kekayaan yang dia tinggalkan dalam keadaan utuh. Sebagai seorang anak, Monkey D. Luffy bermimpi menjadi Raja Bajak Laut. Tapi hidupnya berubah ketika dia secara tidak sengaja mendapatkan kekuatan untuk meregangkan seperti karet...dengan mengorbankan tidak pernah bisa berenang lagi! Sekarang Luffy, dengan bantuan sekumpulan nakama yang beraneka ragam, berangkat untuk mencari "One Piece", yang dikatakan sebagai harta karun terbesar di dunia.',
    'status': 'OnGoing',
    'author': 'ODA Eiichiro',
    'artist': 'ODA Eiichiro',
    'rilis': '1997',
    'awal': 'Chapter Awal: 1',
    'baru': 'Chapter Akhir: 1095',
    'isi': '1095',
    'keterangan': 'on going',
  },
  {
    'imagePath': 'images/blackClover.jpeg',
    'cover': 'images/black clover.jpg',
    'title': 'Black Clover',
    'genre': 'Manga',
    'deskripsi':
        'Manga Black Clover yang dibuat oleh komikus bernama TABATA Yuuki ini bercerita tentang Di dunia yang penuh keajaiban, Asta—anak yatim piatu yang terlalu berisik dan energik—tidak memiliki apa pun. Meskipun demikian, ia bermimpi menjadi Raja Penyihir, gelar yang diberikan kepada penyihir terkuat di Kerajaan Semanggi. Memiliki aspirasi yang sama, teman masa kecil Asta dan saingannya Yuno telah diberkati dengan kemampuan untuk mengendalikan sihir angin yang kuat. Bahkan dengan kesenjangan yang luar biasa di antara mereka, berharap untuk entah bagaimana membangkitkan kemampuan magisnya dan mengejar Yuno, Asta melatih tubuhnya tanpa henti setiap hari. Di Kerajaan Semanggi, setelah seseorang berusia 15 tahun, inilah saatnya bagi mereka untuk menerima Grimoire mereka, item yang memungkinkan penggunanya untuk menggunakan sihir mereka secara maksimal. Pada upacara tersebut, Yuno mendapatkan Grimoire dengan semanggi berdaun empat yang legendaris, yang menunjukkan kekuatan luar biasa dari pemiliknya, sementara Asta menunggunya tanpa tujuan. Merasa sedih, namun tidak mau menyerah, Asta melihat Yuno ditangkap oleh seorang penyihir yang mencoba mencuri Grimoire khusus Yuno. Meskipun sepenuhnya dikuasai oleh penculik Yuno, keinginan Asta untuk terus berjuang menghadiahinya dengan Grimoire-nya sendiri—yang memiliki semanggi hitam berdaun lima yang belum pernah terdengar sebelumnya.',
    'status': 'OnGoing',
    'author': 'TABATA Yuuki',
    'artist': 'TABATA Yuuki',
    'rilis': '2014',
    'awal': 'Chapter Awal: 1',
    'baru': 'Chapter Akhir: 368',
    'isi': '368',
    'keterangan': 'on going',
  },
    // Tambahkan item lainnya sesuai kebutuhan
  ];
  // Data sumber

  // Data sumber
 